### ISSUE TITLE
[Twitter not working] Twitter is trying to get playerID, but fails at it.

### ISSUE THREAD

**Issue by christerjohansson** [DamjanPetrovicki/gcphonev3.1#5]
I get thios message in consol,
`SCRIPT ERROR: @gcphone/server/twitter.lua:247: attempt to call a nil value (global 'GetPlayerID')`

Function in twitter.lua at row 247: GetPlayerID().
This function is not declared anywhere else? Is it a function in FXServer?

**Comment by synceye** [comment]
Hey, this issue should be fixed.

**Comment by christerjohansson** [comment]
"should be fixed"??
It was not working 2 days ago, and there is no update in your repository?

**Comment by synceye** [comment]
I fixed it and it should work now, if you use old esx with essentialmode,
install original version

**Comment by christerjohansson** [comment]
Well,
I am using es_extended 6.4.1 with latest versions of ESX available on Github. Still it does not work, it won't save player och reciever id.

**Comment by synceye** [comment]
You mean you use essentialmode?


sri, 27. svi 2020. u 21:27 Christer Johansson <notifications@github.com>
napisao je:

**Comment by hhyllis** [comment]
Im getting the same error with es_extended v1 final

**Comment by SidVicious99** [comment]
I'm still getting the error using es_extended v1 final as the person above said.
